# Generated by Django 2.2.4 on 2019-09-17 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brief',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
