# Generated by Django 2.2.4 on 2019-09-17 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20190918_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='brief',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brief',
            name='subtitle',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
