# Generated by Django 2.2.4 on 2019-09-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190918_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brief',
            name='author',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
