# Generated by Django 2.2.4 on 2019-09-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190918_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='brief',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
