# Generated by Django 2.2.5 on 2019-10-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class_home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_shown', models.BooleanField(blank=True, default=True, null=True)),
                ('color', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
