# Generated by Django 2.2.5 on 2019-10-01 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class_home',
            new_name='Home',
        ),
    ]
