# Generated by Django 2.2.5 on 2019-10-01 22:49

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191001_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='color',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
