# Generated by Django 2.2.5 on 2019-10-02 13:27

import django.core.validators
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191001_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='e_mail',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AlterField(
            model_name='home',
            name='color',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[home.models.validator]),
        ),
    ]
