# Generated by Django 2.2.5 on 2019-10-02 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20191002_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='e_mail',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.EmailValidator(message='Please, enter corresponding email address')]),
        ),
    ]
