# Generated by Django 2.2.5 on 2019-10-02 21:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20191002_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='url1',
            field=models.URLField(blank=True, max_length=250, null=True, validators=[django.core.validators.URLValidator(message='Please, enter correct address')]),
        ),
    ]
