# Generated by Django 2.2.5 on 2019-10-03 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20191003_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='Title',
            new_name='title',
        ),
    ]
