# Generated by Django 2.2.5 on 2019-10-03 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20191003_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='url1',
            new_name='background_url1',
        ),
        migrations.AddField(
            model_name='home',
            name='background_url2',
            field=models.URLField(blank=True, max_length=250, null=True, validators=[django.core.validators.URLValidator(message='Please, enter correct address')]),
        ),
        migrations.AddField(
            model_name='home',
            name='background_url3',
            field=models.URLField(blank=True, max_length=250, null=True, validators=[django.core.validators.URLValidator(message='Please, enter correct address')]),
        ),
        migrations.AlterField(
            model_name='home',
            name='ico',
            field=models.ImageField(blank=True, null=True, upload_to='ico/'),
        ),
    ]
