# Generated by Django 2.2.5 on 2019-10-03 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20191003_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='background_url1',
            new_name='background_image_url1',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='background_url2',
            new_name='background_image_url2',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='background_url3',
            new_name='background_image_url3',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='color',
            new_name='button_color',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='blog_shown',
            new_name='showing_blog_button',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='ico',
            new_name='website_icon',
        ),
    ]
