# Generated by Django 2.2.5 on 2019-10-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20191003_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='logo',
            field=models.ImageField(blank=True, height_field=200, null=True, upload_to='', width_field=200),
        ),
    ]
