# Generated by Django 2.2.5 on 2019-10-03 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20191003_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='About_link',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator(message='Please, enter correct address')]),
        ),
        migrations.AddField(
            model_name='home',
            name='Contact_link',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator(message='Please, enter correct address')]),
        ),
        migrations.AlterField(
            model_name='home',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
