# Generated by Django 2.2.5 on 2019-10-03 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20191003_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='blog_butt_link',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator]),
        ),
        migrations.AlterField(
            model_name='home',
            name='About_link',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator]),
        ),
        migrations.AlterField(
            model_name='home',
            name='Contact_link',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator]),
        ),
    ]
