# Generated by Django 2.2.5 on 2019-10-03 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20191003_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='blog_butt_link',
        ),
    ]
